[package]
name = "chc_rust"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "chc_rust"

[dependencies]
inventory = "0.3.15"
itertools = "0.13.0"
maturin = "1.6.0"
once_cell = "1.19.0"
pyo3 = { version = "0.22.0", features = ["extension-module"] }
